name: Daily Salmon Permit Checker

on:
  schedule:
    - cron: "0 14 * * *"  # 8 AM MT
  workflow_dispatch:

jobs:
  check-permits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          SMS_GATEWAY: ${{ secrets.SMS_GATEWAY }}
        run: python salmon_permit_alert_bot.py
